// Code generated by the Lingua Franca compiler from:
// file://home/moez/AccountableAI/LFGPT/playground-lingua-franca/examples/C/src/cody-code/TemperatureSensor_improved.lf
#define LOG_LEVEL 2
#define TARGET_FILES_DIRECTORY "/home/moez/AccountableAI/LFGPT/playground-lingua-franca/examples/C/src-gen/cody-code/TemperatureSensor_improved"
#include <limits.h>
#include "include/core/platform.h"
#include "include/api/api.h"
#include "include/core/reactor.h"
#include "include/core/reactor_common.h"
#include "include/core/threaded/scheduler.h"
#include "include/core/mixed_radix.h"
#include "include/core/port.h"
#include "include/core/environment.h"
int lf_reactor_c_main(int argc, const char* argv[]);
int main(int argc, const char* argv[]) {
    return lf_reactor_c_main(argc, argv);
}
void _lf_set_default_command_line_options() {}
#include "_tempsensor.h"
#include "_print.h"
#include "_temperaturesensor_improved_main.h"
typedef enum {
    temperaturesensor_improved_main,
    _num_enclaves
} _enclave_id;
// The global array of environments associated with each enclave
environment_t envs[_num_enclaves];
// 'Create' and initialize the environments in the program
void _lf_create_environments() {
    environment_init(&envs[temperaturesensor_improved_main],temperaturesensor_improved_main,_lf_number_of_workers,1,1,0,0,1,0,0,NULL);
}
// Update the pointer argument to point to the beginning of the environment array
// and return the size of that array
int _lf_get_environments(environment_t ** return_envs) {
   (*return_envs) = (environment_t *) envs;
   return _num_enclaves;
}
// No watchdogs found.
typedef void watchdog_t;
watchdog_t* _lf_watchdogs = NULL;
int _lf_watchdog_count = 0;
void _lf_initialize_trigger_objects() {
    int startup_reaction_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(startup_reaction_count);
    int shutdown_reaction_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(shutdown_reaction_count);
    int reset_reaction_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(reset_reaction_count);
    int timer_triggers_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(timer_triggers_count);
    int modal_state_reset_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(modal_state_reset_count);
    int modal_reactor_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(modal_reactor_count);
    int bank_index;
    SUPPRESS_UNUSED_WARNING(bank_index);
    int watchdog_number = 0;
    SUPPRESS_UNUSED_WARNING(watchdog_number);
    _temperaturesensor_improved_main_main_self_t* temperaturesensor_improved_main_self[1];
    SUPPRESS_UNUSED_WARNING(temperaturesensor_improved_main_self);
    _tempsensor_self_t* temperaturesensor_improved_tempsensor_self[1];
    SUPPRESS_UNUSED_WARNING(temperaturesensor_improved_tempsensor_self);
    _print_self_t* temperaturesensor_improved_print_self[1];
    SUPPRESS_UNUSED_WARNING(temperaturesensor_improved_print_self);
    // ***** Start initializing TemperatureSensor_improved of class TemperatureSensor_improved
    temperaturesensor_improved_main_self[0] = new__temperaturesensor_improved_main();
    temperaturesensor_improved_main_self[0]->base.environment = &envs[temperaturesensor_improved_main];
    bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
    SUPPRESS_UNUSED_WARNING(_lf_watchdog_count);
    {
        // ***** Start initializing TemperatureSensor_improved.tempSensor of class TempSensor
        temperaturesensor_improved_tempsensor_self[0] = new__tempsensor();
        temperaturesensor_improved_tempsensor_self[0]->base.environment = &envs[temperaturesensor_improved_main];
        bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
        // width of -2 indicates that it is not a multiport.
        temperaturesensor_improved_tempsensor_self[0]->_lf_temp_width = -2;
        envs[temperaturesensor_improved_main].startup_reactions[startup_reaction_count[temperaturesensor_improved_main]++] = &temperaturesensor_improved_tempsensor_self[0]->_lf__reaction_0;
        SUPPRESS_UNUSED_WARNING(_lf_watchdog_count);
        // Initiaizing timer TemperatureSensor_improved.tempSensor.myTimer.
        temperaturesensor_improved_tempsensor_self[0]->_lf__myTimer.offset = 0;
        temperaturesensor_improved_tempsensor_self[0]->_lf__myTimer.period = SEC(1);
        // Associate timer with the environment of its parent
        envs[temperaturesensor_improved_main].timer_triggers[timer_triggers_count[temperaturesensor_improved_main]++] = &temperaturesensor_improved_tempsensor_self[0]->_lf__myTimer;
        temperaturesensor_improved_tempsensor_self[0]->_lf__myTimer.mode = NULL;
        temperaturesensor_improved_tempsensor_self[0]->_lf__reaction_0.deadline = NEVER;
        temperaturesensor_improved_tempsensor_self[0]->_lf__reaction_1.deadline = NEVER;
        //***** End initializing TemperatureSensor_improved.tempSensor
    }
    {
        // ***** Start initializing TemperatureSensor_improved.print of class Print
        temperaturesensor_improved_print_self[0] = new__print();
        temperaturesensor_improved_print_self[0]->base.environment = &envs[temperaturesensor_improved_main];
        bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
        // width of -2 indicates that it is not a multiport.
        temperaturesensor_improved_print_self[0]->_lf_in_width = -2;
        SUPPRESS_UNUSED_WARNING(_lf_watchdog_count);
        temperaturesensor_improved_print_self[0]->_lf__reaction_0.deadline = NEVER;
        //***** End initializing TemperatureSensor_improved.print
    }
    //***** End initializing TemperatureSensor_improved
    // **** Start deferred initialize for TemperatureSensor_improved
    {
        // **** Start deferred initialize for TemperatureSensor_improved.tempSensor
        {
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_0 of TemperatureSensor_improved.tempSensor.
            temperaturesensor_improved_tempsensor_self[0]->_lf__reaction_0.num_outputs = 1;
            // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
            // struct for this reaction.
            temperaturesensor_improved_tempsensor_self[0]->_lf__reaction_0.triggers = (trigger_t***)_lf_allocate(
                    1, sizeof(trigger_t**),
                    &temperaturesensor_improved_tempsensor_self[0]->base.allocations);
            temperaturesensor_improved_tempsensor_self[0]->_lf__reaction_0.triggered_sizes = (int*)_lf_allocate(
                    1, sizeof(int),
                    &temperaturesensor_improved_tempsensor_self[0]->base.allocations);
            temperaturesensor_improved_tempsensor_self[0]->_lf__reaction_0.output_produced = (bool**)_lf_allocate(
                    1, sizeof(bool*),
                    &temperaturesensor_improved_tempsensor_self[0]->base.allocations);
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
                {
                    temperaturesensor_improved_tempsensor_self[0]->_lf__reaction_0.output_produced[count++] = &temperaturesensor_improved_tempsensor_self[0]->_lf_temp.is_present;
                }
            }
            
            // ** End initialization for reaction 0 of TemperatureSensor_improved.tempSensor
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_1 of TemperatureSensor_improved.tempSensor.
            temperaturesensor_improved_tempsensor_self[0]->_lf__reaction_1.num_outputs = 1;
            // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
            // struct for this reaction.
            temperaturesensor_improved_tempsensor_self[0]->_lf__reaction_1.triggers = (trigger_t***)_lf_allocate(
                    1, sizeof(trigger_t**),
                    &temperaturesensor_improved_tempsensor_self[0]->base.allocations);
            temperaturesensor_improved_tempsensor_self[0]->_lf__reaction_1.triggered_sizes = (int*)_lf_allocate(
                    1, sizeof(int),
                    &temperaturesensor_improved_tempsensor_self[0]->base.allocations);
            temperaturesensor_improved_tempsensor_self[0]->_lf__reaction_1.output_produced = (bool**)_lf_allocate(
                    1, sizeof(bool*),
                    &temperaturesensor_improved_tempsensor_self[0]->base.allocations);
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
                {
                    temperaturesensor_improved_tempsensor_self[0]->_lf__reaction_1.output_produced[count++] = &temperaturesensor_improved_tempsensor_self[0]->_lf_temp.is_present;
                }
            }
            
            // ** End initialization for reaction 1 of TemperatureSensor_improved.tempSensor
        }
        // **** End of deferred initialize for TemperatureSensor_improved.tempSensor
        // **** Start deferred initialize for TemperatureSensor_improved.print
        {
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_0 of TemperatureSensor_improved.print.
            temperaturesensor_improved_print_self[0]->_lf__reaction_0.num_outputs = 0;
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
            }
            
            // ** End initialization for reaction 0 of TemperatureSensor_improved.print
        }
        // **** End of deferred initialize for TemperatureSensor_improved.print
    }
    // **** End of deferred initialize for TemperatureSensor_improved
    // **** Start non-nested deferred initialize for TemperatureSensor_improved
    // **** Start non-nested deferred initialize for TemperatureSensor_improved.tempSensor
    // For reference counting, set num_destinations for port TemperatureSensor_improved.tempSensor.temp.
    // Iterate over range TemperatureSensor_improved.tempSensor.temp(0,1)->[TemperatureSensor_improved.print.in(0,1)].
    {
        int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
        int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
        int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
        int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
        temperaturesensor_improved_tempsensor_self[src_runtime]->_lf_temp._base.num_destinations = 1;
        temperaturesensor_improved_tempsensor_self[src_runtime]->_lf_temp._base.source_reactor = (self_base_t*)temperaturesensor_improved_tempsensor_self[src_runtime];
    }
    {
        int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
        // Iterate over range TemperatureSensor_improved.tempSensor.temp(0,1)->[TemperatureSensor_improved.print.in(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            // Reaction 0 of TemperatureSensor_improved.tempSensor triggers 1 downstream reactions
            // through port TemperatureSensor_improved.tempSensor.temp.
            temperaturesensor_improved_tempsensor_self[src_runtime]->_lf__reaction_0.triggered_sizes[triggers_index[src_runtime]] = 1;
            // For reaction 0 of TemperatureSensor_improved.tempSensor, allocate an
            // array of trigger pointers for downstream reactions through port TemperatureSensor_improved.tempSensor.temp
            trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                    1, sizeof(trigger_t*),
                    &temperaturesensor_improved_tempsensor_self[src_runtime]->base.allocations); 
            temperaturesensor_improved_tempsensor_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime]++] = trigger_array;
        }
        for (int i = 0; i < 1; i++) triggers_index[i] = 0;
        // Iterate over ranges TemperatureSensor_improved.tempSensor.temp(0,1)->[TemperatureSensor_improved.print.in(0,1)] and TemperatureSensor_improved.print.in(0,1).
        {
            int src_runtime = 0; // Runtime index.
            SUPPRESS_UNUSED_WARNING(src_runtime);
            int src_channel = 0; // Channel index.
            SUPPRESS_UNUSED_WARNING(src_channel);
            int src_bank = 0; // Bank index.
            SUPPRESS_UNUSED_WARNING(src_bank);
            // Iterate over range TemperatureSensor_improved.print.in(0,1).
            {
                int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Point to destination port TemperatureSensor_improved.print.in's trigger struct.
                temperaturesensor_improved_tempsensor_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime] + src_channel][0] = &temperaturesensor_improved_print_self[dst_runtime]->_lf__in;
            }
        }
    }
    {
        int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
        // Iterate over range TemperatureSensor_improved.tempSensor.temp(0,1)->[TemperatureSensor_improved.print.in(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            // Reaction 1 of TemperatureSensor_improved.tempSensor triggers 1 downstream reactions
            // through port TemperatureSensor_improved.tempSensor.temp.
            temperaturesensor_improved_tempsensor_self[src_runtime]->_lf__reaction_1.triggered_sizes[triggers_index[src_runtime]] = 1;
            // For reaction 1 of TemperatureSensor_improved.tempSensor, allocate an
            // array of trigger pointers for downstream reactions through port TemperatureSensor_improved.tempSensor.temp
            trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                    1, sizeof(trigger_t*),
                    &temperaturesensor_improved_tempsensor_self[src_runtime]->base.allocations); 
            temperaturesensor_improved_tempsensor_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime]++] = trigger_array;
        }
        for (int i = 0; i < 1; i++) triggers_index[i] = 0;
        // Iterate over ranges TemperatureSensor_improved.tempSensor.temp(0,1)->[TemperatureSensor_improved.print.in(0,1)] and TemperatureSensor_improved.print.in(0,1).
        {
            int src_runtime = 0; // Runtime index.
            SUPPRESS_UNUSED_WARNING(src_runtime);
            int src_channel = 0; // Channel index.
            SUPPRESS_UNUSED_WARNING(src_channel);
            int src_bank = 0; // Bank index.
            SUPPRESS_UNUSED_WARNING(src_bank);
            // Iterate over range TemperatureSensor_improved.print.in(0,1).
            {
                int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Point to destination port TemperatureSensor_improved.print.in's trigger struct.
                temperaturesensor_improved_tempsensor_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime] + src_channel][0] = &temperaturesensor_improved_print_self[dst_runtime]->_lf__in;
            }
        }
    }
    // **** End of non-nested deferred initialize for TemperatureSensor_improved.tempSensor
    // **** Start non-nested deferred initialize for TemperatureSensor_improved.print
    // **** End of non-nested deferred initialize for TemperatureSensor_improved.print
    // **** End of non-nested deferred initialize for TemperatureSensor_improved
    // Connect inputs and outputs for reactor TemperatureSensor_improved.
    // Connect inputs and outputs for reactor TemperatureSensor_improved.tempSensor.
    // Connect TemperatureSensor_improved.tempSensor.temp(0,1)->[TemperatureSensor_improved.print.in(0,1)] to port TemperatureSensor_improved.print.in(0,1)
    // Iterate over ranges TemperatureSensor_improved.tempSensor.temp(0,1)->[TemperatureSensor_improved.print.in(0,1)] and TemperatureSensor_improved.print.in(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range TemperatureSensor_improved.print.in(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            temperaturesensor_improved_print_self[dst_runtime]->_lf_in = (_print_in_t*)&temperaturesensor_improved_tempsensor_self[src_runtime]->_lf_temp;
        }
    }
    // Connect inputs and outputs for reactor TemperatureSensor_improved.print.
    {
    }
    {
    }
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            // Add port TemperatureSensor_improved.tempSensor.temp to array of is_present fields.
            envs[temperaturesensor_improved_main].is_present_fields[0 + count] = &temperaturesensor_improved_tempsensor_self[0]->_lf_temp.is_present;
            #ifdef FEDERATED_DECENTRALIZED
            // Add port TemperatureSensor_improved.tempSensor.temp to array of intended_tag fields.
            envs[temperaturesensor_improved_main]._lf_intended_tag_fields[0 + count] = &temperaturesensor_improved_tempsensor_self[0]->_lf_temp.intended_tag;
            #endif // FEDERATED_DECENTRALIZED
            count++;
        }
    }
    // Set reaction priorities for ReactorInstance TemperatureSensor_improved
    {
        // Set reaction priorities for ReactorInstance TemperatureSensor_improved.tempSensor
        {
            temperaturesensor_improved_tempsensor_self[0]->_lf__reaction_0.chain_id = 1;
            // index is the OR of level 0 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            temperaturesensor_improved_tempsensor_self[0]->_lf__reaction_0.index = 0xffffffffffff0000LL;
            temperaturesensor_improved_tempsensor_self[0]->_lf__reaction_1.chain_id = 1;
            // index is the OR of level 1 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            temperaturesensor_improved_tempsensor_self[0]->_lf__reaction_1.index = 0xffffffffffff0001LL;
        }
        // Set reaction priorities for ReactorInstance TemperatureSensor_improved.print
        {
            temperaturesensor_improved_print_self[0]->_lf__reaction_0.chain_id = 1;
            // index is the OR of level 2 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            temperaturesensor_improved_print_self[0]->_lf__reaction_0.index = 0xffffffffffff0002LL;
        }
    }
    // Initialize the scheduler
    size_t num_reactions_per_level[3] = 
        {1, 1, 1};
    sched_params_t sched_params = (sched_params_t) {
                            .num_reactions_per_level = &num_reactions_per_level[0],
                            .num_reactions_per_level_size = (size_t) 3};
    lf_sched_init(
        &envs[temperaturesensor_improved_main],
        envs[temperaturesensor_improved_main].num_workers,
        &sched_params
    );
    #ifdef EXECUTABLE_PREAMBLE
    _lf_executable_preamble(&envs[0]);
    #endif
    #ifdef FEDERATED
    initialize_triggers_for_federate();
    #endif // FEDERATED
}
void logical_tag_complete(tag_t tag_to_send) {
#ifdef FEDERATED_CENTRALIZED
        _lf_logical_tag_complete(tag_to_send);
#endif // FEDERATED_CENTRALIZED
}
#ifndef FEDERATED
void terminate_execution(environment_t* env) {}
#endif
