#include "include/api/api.h"
#include "include/LowCode-ChatGPT_1/RandomArray.h"
#include "_randomarray.h"
// *********** From the preamble, verbatim:
#line 97 "/home/moez/AccountableAI/LFGPT/playground-lingua-franca/examples/C/src/low-code/LowCode-ChatGPT_1.lf"
    // GENERATED BY ChatGPT:
    #include <stdlib.h>
    #include <time.h>

   // Define a function to generate a random integer between min and max (inclusive).
int generateRandomInt(int min, int max) {
    return min + rand() % (max - min + 1);
}

// *********** End of preamble.
// ***** Start of method declarations.
// ***** End of method declarations.
#include "include/api/set.h"
void _randomarrayreaction_function_0(void* instance_args) {
    _randomarray_self_t* self = (_randomarray_self_t*)instance_args; SUPPRESS_UNUSED_WARNING(self);
    _randomarray_out_t* out = &self->_lf_out;
    #line 108 "/home/moez/AccountableAI/LFGPT/playground-lingua-franca/examples/C/src/low-code/LowCode-ChatGPT_1.lf"
    // GENERATED BY ChatGPT:
    // Seed the random number generator with the current time
    srand((unsigned int)lf_time_physical());
    
    // Allocate memory for the output array.
    int length = 10;
    int* resultArray = (int*)malloc(length * sizeof(int));
    
    if (resultArray != NULL) {
        // Generate random integers and store them in the array.
        for (int i = 0; i < length; i++) {
            resultArray[i] = generateRandomInt(0, 100);
        }
    
        // Produce the array as an output.
        lf_set_array(outputPort, resultArray, length);
    }
}
#include "include/api/set_undef.h"
_randomarray_self_t* new__randomarray() {
    _randomarray_self_t* self = (_randomarray_self_t*)_lf_new_reactor(sizeof(_randomarray_self_t));
    #line 107 "/home/moez/AccountableAI/LFGPT/playground-lingua-franca/examples/C/src/low-code/LowCode-ChatGPT_1.lf"
    self->_lf__reaction_0.number = 0;
    #line 107 "/home/moez/AccountableAI/LFGPT/playground-lingua-franca/examples/C/src/low-code/LowCode-ChatGPT_1.lf"
    self->_lf__reaction_0.function = _randomarrayreaction_function_0;
    #line 107 "/home/moez/AccountableAI/LFGPT/playground-lingua-franca/examples/C/src/low-code/LowCode-ChatGPT_1.lf"
    self->_lf__reaction_0.self = self;
    #line 107 "/home/moez/AccountableAI/LFGPT/playground-lingua-franca/examples/C/src/low-code/LowCode-ChatGPT_1.lf"
    self->_lf__reaction_0.deadline_violation_handler = NULL;
    #line 107 "/home/moez/AccountableAI/LFGPT/playground-lingua-franca/examples/C/src/low-code/LowCode-ChatGPT_1.lf"
    self->_lf__reaction_0.STP_handler = NULL;
    #line 107 "/home/moez/AccountableAI/LFGPT/playground-lingua-franca/examples/C/src/low-code/LowCode-ChatGPT_1.lf"
    self->_lf__reaction_0.name = "?";
    #line 107 "/home/moez/AccountableAI/LFGPT/playground-lingua-franca/examples/C/src/low-code/LowCode-ChatGPT_1.lf"
    self->_lf__reaction_0.mode = NULL;
    #ifdef FEDERATED_DECENTRALIZED
    self->_lf__startup.intended_tag = (tag_t) { .time = NEVER, .microstep = 0u};
    #endif // FEDERATED_DECENTRALIZED
    self->_lf__startup_reactions[0] = &self->_lf__reaction_0;
    self->_lf__startup.last = NULL;
    self->_lf__startup.reactions = &self->_lf__startup_reactions[0];
    self->_lf__startup.number_of_reactions = 1;
    self->_lf__startup.is_timer = false;
    return self;
}
