#include "include/api/api.h"
#include "include/LowCode-Cody_2/RandomArray.h"
#include "_randomarray.h"
// *********** From the preamble, verbatim:
#line 84 "/home/moez/AccountableAI/LFGPT/playground-lingua-franca/examples/C/src/low-code/LowCode-Cody_2.lf"
// GENERATED BY Cody, after a second try. In the first try, it didn't generate the includes and the srand() function:
#include <stdlib.h>
#include <time.h>

// Seed random number generator
srand(time(NULL));

// Generate array
int length = 10;
int* array = (int*) malloc(length * sizeof(int));

for (int i = 0; i < length; i++) {
  array[i] = rand() % 101; // Random int between 0 and 100
}

// Set output
lf_set_array(out, array, length);

// *********** End of preamble.
// ***** Start of method declarations.
// ***** End of method declarations.
_randomarray_self_t* new__randomarray() {
    _randomarray_self_t* self = (_randomarray_self_t*)_lf_new_reactor(sizeof(_randomarray_self_t));

    return self;
}
