#include "include/api/api.h"
#include "include/LowCode/RandomArray.h"
#include "_randomarray.h"
// *********** From the preamble, verbatim:
#line 84 "/home/moez/AccountableAI/LFGPT/playground-lingua-franca/examples/C/src/low-code/LowCode.lf"
// GENERATED BY ChatGPT:
#include <stdlib.h>
#include <time.h>

// Function to generate a random integer between min and max
int generateRandomInt(int min, int max) {
  return min + rand() % (max - min + 1);
}

// *********** End of preamble.
// ***** Start of method declarations.
// ***** End of method declarations.
#include "include/api/set.h"
void _randomarrayreaction_function_0(void* instance_args) {
    _randomarray_self_t* self = (_randomarray_self_t*)instance_args; SUPPRESS_UNUSED_WARNING(self);
    _randomarray_out_t* out = &self->_lf_out;
    #line 95 "/home/moez/AccountableAI/LFGPT/playground-lingua-franca/examples/C/src/low-code/LowCode.lf"
    // GENERATED BY ChatGPT:
    // Seed the random number generator with the current time
    srand((unsigned int)time(NULL));
    
    // Define the length of the output array
    int length = 10;
    
    // Allocate memory for the output array
    int *outputArray = (int *)malloc(length * sizeof(int));
    
    if (outputArray == NULL) {
      // Handle memory allocation error
      return;
    }
    
    // Generate random integers between 0 and 100 and store them in the output array
    for (int i = 0; i < length; i++) {
      outputArray[i] = generateRandomInt(0, 100);
    }
    
    // Set the output array on the out port
    lf_set_array(out, outputArray, length);
}
#include "include/api/set_undef.h"
_randomarray_self_t* new__randomarray() {
    _randomarray_self_t* self = (_randomarray_self_t*)_lf_new_reactor(sizeof(_randomarray_self_t));
    #line 94 "/home/moez/AccountableAI/LFGPT/playground-lingua-franca/examples/C/src/low-code/LowCode.lf"
    self->_lf__reaction_0.number = 0;
    #line 94 "/home/moez/AccountableAI/LFGPT/playground-lingua-franca/examples/C/src/low-code/LowCode.lf"
    self->_lf__reaction_0.function = _randomarrayreaction_function_0;
    #line 94 "/home/moez/AccountableAI/LFGPT/playground-lingua-franca/examples/C/src/low-code/LowCode.lf"
    self->_lf__reaction_0.self = self;
    #line 94 "/home/moez/AccountableAI/LFGPT/playground-lingua-franca/examples/C/src/low-code/LowCode.lf"
    self->_lf__reaction_0.deadline_violation_handler = NULL;
    #line 94 "/home/moez/AccountableAI/LFGPT/playground-lingua-franca/examples/C/src/low-code/LowCode.lf"
    self->_lf__reaction_0.STP_handler = NULL;
    #line 94 "/home/moez/AccountableAI/LFGPT/playground-lingua-franca/examples/C/src/low-code/LowCode.lf"
    self->_lf__reaction_0.name = "?";
    #line 94 "/home/moez/AccountableAI/LFGPT/playground-lingua-franca/examples/C/src/low-code/LowCode.lf"
    self->_lf__reaction_0.mode = NULL;
    #ifdef FEDERATED_DECENTRALIZED
    self->_lf__startup.intended_tag = (tag_t) { .time = NEVER, .microstep = 0u};
    #endif // FEDERATED_DECENTRALIZED
    self->_lf__startup_reactions[0] = &self->_lf__reaction_0;
    self->_lf__startup.last = NULL;
    self->_lf__startup.reactions = &self->_lf__startup_reactions[0];
    self->_lf__startup.number_of_reactions = 1;
    self->_lf__startup.is_timer = false;
    return self;
}
