#include "include/api/api.h"
#include "include/LowCode/Sort.h"
#include "_sort.h"
// *********** From the preamble, verbatim:
#line 138 "/home/moez/AccountableAI/LFGPT/playground-lingua-franca/examples/C/src/low-code/LowCode.lf"
// GENERATED BY ChatGPT:
#include <stdlib.h>

// Function to compare integers for qsort
int compareIntegers(const void *a, const void *b) {
  return (*(int *)a - *(int *)b);
}

// *********** End of preamble.
// ***** Start of method declarations.
// ***** End of method declarations.
#include "include/api/set.h"
void _sortreaction_function_0(void* instance_args) {
    _sort_self_t* self = (_sort_self_t*)instance_args; SUPPRESS_UNUSED_WARNING(self);
    _sort_in_t* in = self->_lf_in;
    if (in->is_present) {
        in->length = in->token->length;
        in->value = (int*)in->token->value;
    } else {
        in->length = 0;
    }
    int in_width = self->_lf_in_width; SUPPRESS_UNUSED_WARNING(in_width);
    _sort_out_t* out = &self->_lf_out;
    #line 148 "/home/moez/AccountableAI/LFGPT/playground-lingua-franca/examples/C/src/low-code/LowCode.lf"
    // GENERATED BY ChatGPT after a second try in which I reminded ChatGPT that in is a pointer.
    if (in->is_present) {
      // Determine the length of the input array
      int length = in->length;
    
      // Allocate memory for a new array to store the sorted values
      int *sortedArray = (int *)malloc(length * sizeof(int));
    
      if (sortedArray == NULL) {
          // Handle memory allocation error
          return;
      }
    
      // Copy the values from the input array to the new array
      for (int i = 0; i < length; i++) {
          sortedArray[i] = in->value[i];
      }
    
      // Sort the new array in ascending order using qsort
      qsort(sortedArray, length, sizeof(int), compareIntegers);
    
      // Set the sorted array on the out port
      lf_set_array(out, sortedArray, length);
    }
}
#include "include/api/set_undef.h"
_sort_self_t* new__sort() {
    _sort_self_t* self = (_sort_self_t*)_lf_new_reactor(sizeof(_sort_self_t));
    #line 121 "/home/moez/AccountableAI/LFGPT/playground-lingua-franca/examples/C/src/low-code/LowCode.lf"
    // Set input by default to an always absent default input.
    #line 121 "/home/moez/AccountableAI/LFGPT/playground-lingua-franca/examples/C/src/low-code/LowCode.lf"
    self->_lf_in = &self->_lf_default__in;
    #line 121 "/home/moez/AccountableAI/LFGPT/playground-lingua-franca/examples/C/src/low-code/LowCode.lf"
    // Set the default source reactor pointer
    #line 121 "/home/moez/AccountableAI/LFGPT/playground-lingua-franca/examples/C/src/low-code/LowCode.lf"
    self->_lf_default__in._base.source_reactor = (self_base_t*)self;
    #line 147 "/home/moez/AccountableAI/LFGPT/playground-lingua-franca/examples/C/src/low-code/LowCode.lf"
    self->_lf__reaction_0.number = 0;
    #line 147 "/home/moez/AccountableAI/LFGPT/playground-lingua-franca/examples/C/src/low-code/LowCode.lf"
    self->_lf__reaction_0.function = _sortreaction_function_0;
    #line 147 "/home/moez/AccountableAI/LFGPT/playground-lingua-franca/examples/C/src/low-code/LowCode.lf"
    self->_lf__reaction_0.self = self;
    #line 147 "/home/moez/AccountableAI/LFGPT/playground-lingua-franca/examples/C/src/low-code/LowCode.lf"
    self->_lf__reaction_0.deadline_violation_handler = NULL;
    #line 147 "/home/moez/AccountableAI/LFGPT/playground-lingua-franca/examples/C/src/low-code/LowCode.lf"
    self->_lf__reaction_0.STP_handler = NULL;
    #line 147 "/home/moez/AccountableAI/LFGPT/playground-lingua-franca/examples/C/src/low-code/LowCode.lf"
    self->_lf__reaction_0.name = "?";
    #line 147 "/home/moez/AccountableAI/LFGPT/playground-lingua-franca/examples/C/src/low-code/LowCode.lf"
    self->_lf__reaction_0.mode = NULL;
    #line 121 "/home/moez/AccountableAI/LFGPT/playground-lingua-franca/examples/C/src/low-code/LowCode.lf"
    self->_lf__in.last = NULL;
    #line 121 "/home/moez/AccountableAI/LFGPT/playground-lingua-franca/examples/C/src/low-code/LowCode.lf"
    #ifdef FEDERATED_DECENTRALIZED
    #line 121 "/home/moez/AccountableAI/LFGPT/playground-lingua-franca/examples/C/src/low-code/LowCode.lf"
    self->_lf__in.intended_tag = (tag_t) { .time = NEVER, .microstep = 0u};
    #line 121 "/home/moez/AccountableAI/LFGPT/playground-lingua-franca/examples/C/src/low-code/LowCode.lf"
    #endif // FEDERATED_DECENTRALIZED
    #line 121 "/home/moez/AccountableAI/LFGPT/playground-lingua-franca/examples/C/src/low-code/LowCode.lf"
    #line 121 "/home/moez/AccountableAI/LFGPT/playground-lingua-franca/examples/C/src/low-code/LowCode.lf"
    self->_lf__in_reactions[0] = &self->_lf__reaction_0;
    #line 121 "/home/moez/AccountableAI/LFGPT/playground-lingua-franca/examples/C/src/low-code/LowCode.lf"
    self->_lf__in.reactions = &self->_lf__in_reactions[0];
    #line 121 "/home/moez/AccountableAI/LFGPT/playground-lingua-franca/examples/C/src/low-code/LowCode.lf"
    self->_lf__in.number_of_reactions = 1;
    #line 121 "/home/moez/AccountableAI/LFGPT/playground-lingua-franca/examples/C/src/low-code/LowCode.lf"
    #ifdef FEDERATED
    #line 121 "/home/moez/AccountableAI/LFGPT/playground-lingua-franca/examples/C/src/low-code/LowCode.lf"
    self->_lf__in.physical_time_of_arrival = NEVER;
    #line 121 "/home/moez/AccountableAI/LFGPT/playground-lingua-franca/examples/C/src/low-code/LowCode.lf"
    #endif // FEDERATED
    self->_lf__in.tmplt.type.element_size = sizeof(int);
    return self;
}
